events {}

http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    auth_basic "CE Tracker – Authorized Users Only";
    auth_basic_user_file /etc/nginx/.htpasswd;

    location / {
      try_files $uri $uri/ =404;
    }

    location = /logout {
      add_header WWW-Authenticate 'Basic realm="CE Tracker – Logged Out"' always;
      return 401;
    }
  }

